# Unique project identification
sonar.projectKey=viveksingh2893
sonar.projectName=Vivek Singh
sonar.projectVersion=1.0.0

# Path to the source code (usually 'src' or the root folder)
sonar.sources=.
sonar.exclusions=node_modules/**, android/**, ios/**, coverage/**, __tests__/**, .bundle/**

# Language settings
sonar.sourceEncoding=UTF-8
sonar.javascript.environments=react-native

# Code Coverage (Optional: if using Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info